### ISSUE TITLE
Source Sans is not outlined in some module captures 

### ISSUE THREAD

**Issue by martgnz** [PopulateTools/gobierto.es#55]
So it looks like this when you don't have the font installed (Firefox 57):

### Module views

<img width="682" alt="screen shot 2017-11-14 at 08 49 57" src="https://user-images.githubusercontent.com/1236790/32770860-f06e49aa-c918-11e7-9e98-0f4bb07c6198.png">

<img width="683" alt="screen shot 2017-11-14 at 08 51 25" src="https://user-images.githubusercontent.com/1236790/32771047-6849c454-c919-11e7-9114-7255e06d38c1.png">

<img width="680" alt="screen shot 2017-11-14 at 08 51 38" src="https://user-images.githubusercontent.com/1236790/32771054-70ee4508-c919-11e7-9378-4b1c2292d2ba.png">

<img width="703" alt="screen shot 2017-11-14 at 08 51 48" src="https://user-images.githubusercontent.com/1236790/32771082-8dbaec68-c919-11e7-968c-98ed1fbdcb3b.png">

### On the frontpage too

<img width="753" alt="screen shot 2017-11-14 at 08 52 22" src="https://user-images.githubusercontent.com/1236790/32770983-436fbb70-c919-11e7-8a1f-354331b0072c.png">

<img width="608" alt="screen shot 2017-11-14 at 08 52 37" src="https://user-images.githubusercontent.com/1236790/32771009-48459a0c-c919-11e7-9e55-5dcfa6c97b16.png">

Otherwise, great design! Keep it up 👍

**Comment by javierarce** [comment]
Thanks, @martgnz ❤️
